### ISSUE TITLE
Not working with Sencha Ext JS 6.2.1 

### ISSUE THREAD

**Issue by SumanBhowmick** [elmasse/elmasse-bundle#28]
Hi,

I have run into a problem while using elmasse-bundle with Sencha Ext JS v6.2.1 application. I am aware that currently there is no support for MVC architecture, but I was still able to somehow use this bundle in an MVC application having Sencha Ext JS version 6.0.2 with a few compromises, that I was OK with. But now I am unable to run the same MVC application having Sencha Ext JS version 6.2.1. 

I didn't use 'sencha app upgrade' cmd for upgrading my application, instead I generated a fresh Sencha Ext JS v6.2.1 application and copied all MVC files. I followed all the steps in the documentation to install a fresh copy of elmasse-bundle. But I am getting the following error while running the app in the browser.

`
Uncaught TypeError: me.getConfigurator is not a function(…)        Bundle.js?_dc=1480744665177:278
`

![elmasse](https://cloud.githubusercontent.com/assets/18117510/20857424/06d00a30-b952-11e6-9a32-566bb2a34174.jpg)

No idea whats's going wrong!! 

Thanks In Advance.

**Comment by elmasse** [comment]
Check out this branch: https://github.com/elmasse/elmasse-bundle/tree/ext6.2
Just didn't find the time to merge to master and publish a new package build yet.
